org 100h

INCLUDE "EMU8086.INC"

MOV     DX, OFFSET MAIN
MOV     AH, 9
INT     21H

MOV     DX, OFFSET MESSAGE
MOV     AH, 9
INT     21H
CALL    SCAN_NUM
MOV     RADIUS,CX

MOV     AX, 1
MOV     AX, NUM
MUL     RADIUS
MUL     RADIUS
MUL     RADIUS
DIV     DEN

CALL    pthis
        db 13,10, "THE VOLUME (APPROX.) IS : ",0
CALL    PRINT_NUM        

ret
RADIUS DW ?
NUM DW 88
DEN DW 21
MAIN DB "PROGRAM CALCULATES THE VOLUME OF A SPHERE. $"
MESSAGE DB 13,10, "ENTER THE RADIUS: $"

DEFINE_PTHIS
DEFINE_SCAN_NUM
DEFINE_PRINT_NUM
DEFINE_PRINT_NUM_UNS
